version: "3.5"

services:
  copier:
    image: ghcr.io/datf/copier-runner:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: copier
    volumes:
      - .:/app
